<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>hiuh</string>
        <string>hiue</string>
    </array>
    <key>name</key>
    <string>hiuh</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>^\s*\..*$</string>
            <key>name</key>
            <string>comment.line.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>"[^"]*"</string>
            <key>name</key>
            <string>string.quoted.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>'[^']*'</string>
            <key>name</key>
            <string>string.quoted.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(SANT|FALSKT)\b</string>
            <key>name</key>
            <string>constant.language.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>-?\d+(,\d+)?</string>
            <key>name</key>
            <string>constant.numeric.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\bskriv\b</string>
            <key>name</key>
            <string>support.function.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\bom\b</string>
            <key>name</key>
            <string>keyword.control.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\bmedan\b</string>
            <key>name</key>
            <string>keyword.control.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\bannars\b</string>
            <key>name</key>
            <string>keyword.control.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\bförsök\b</string>
            <key>name</key>
            <string>keyword.control.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\bfånga\b</string>
            <key>name</key>
            <string>keyword.control.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\bkasta\b</string>
            <key>name</key>
            <string>keyword.control.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\bsätt\b</string>
            <key>name</key>
            <string>keyword.declaration.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\btyp\b</string>
            <key>name</key>
            <string>keyword.declaration.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\bgrej\b</string>
            <key>name</key>
            <string>keyword.function.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\bge\b</string>
            <key>name</key>
            <string>keyword.return.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\bmed\b</string>
            <key>name</key>
            <string>keyword.other.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\böppna\b</string>
            <key>name</key>
            <string>keyword.other.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\bstäng\b</string>
            <key>name</key>
            <string>keyword.other.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\banvänd\b</string>
            <key>name</key>
            <string>keyword.import.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(större|mindre|lika)\b</string>
            <key>name</key>
            <string>keyword.operator.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(än|eller|och)\b</string>
            <key>name</key>
            <string>keyword.operator.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\bär\b</string>
            <key>name</key>
            <string>keyword.operator.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(plus|minus|gånger|delat)\b</string>
            <key>name</key>
            <string>keyword.operator.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(till|från|i|som|lista)\b</string>
            <key>name</key>
            <string>keyword.other.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.hiuh</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b[a-zA-ZåäöÅÄÖüÜéèêëàâäáãåæçìíîïùúûüôöõøœñýÿšžćčżšžåäöüß]+\b</string>
            <key>name</key>
            <string>variable.other.hiuh</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.hiuh</string>
    <key>uuid</key>
    <string>a1b2c3d4-e5f6-7890-abcd-ef1234567890</string>
</dict>
</plist>